;
; global custom
;
[esp32idf_custom]
#platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
extra_scripts =
  pre:scripts/pre_generate_crt_asm.py
  pre:scripts/clean_idf_artifacts.py

; ==============================
; sdkconfig for ESP32/IDF based boards
; ==============================

[sdkcfg_wifi_off]
custom_sdkconfig =
  CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_80=y
  CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ=80
  CONFIG_PM_ENABLE=y
  CONFIG_ESP_BROWNOUT_DET=y
  CONFIG_ESP_BROWNOUT_DET_LVL=6
  CONFIG_ESP_PHY_MAX_WIFI_TX_POWER=8
  CONFIG_ESP_PHY_MAX_TX_POWER=8
  CONFIG_ESP_PHY_REDUCE_TX_POWER=y
  CONFIG_ESP_PHY_RF_CAL_PARTIAL=y
  CONFIG_BT_ENABLED=y
  CONFIG_BT_BLE_ENABLED=y
  CONFIG_BT_CLASSIC_ENABLED=n
  CONFIG_BT_BLE_42_FEATURES_SUPPORTED=y
  CONFIG_BT_NIMBLE_ENABLED=y
  CONFIG_BT_NIMBLE_MAX_CONNECTIONS=3
  CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_INTERNAL=y
  CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_EFF=0
  CONFIG_ESP_TASK_WDT_TIMEOUT_S=10
  CONFIG_ESP_WIFI_ENABLED=n
  CONFIG_ESP_WIFI_SOFTAP_SUPPORT=n
  CONFIG_ESP_WIFI_NAN_ENABLE=n
  CONFIG_ESP_COEX_ENABLED=n
  CONFIG_ESP_WIFI_COEXIST_ENABLE=n
  CONFIG_ESP_WIFI_STATION_ROAMING_EXT_CALIBRATION=n
  CONFIG_ESP_INSIGHTS_ENABLED=n
  CONFIG_ESP_DIAGNOSTICS_ENABLED=n

[sdkcfg_wifi_on]
custom_sdkconfig =
  CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_80=y
  CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ=80
  CONFIG_PM_ENABLE=y
  CONFIG_ESP_BROWNOUT_DET=y
  CONFIG_ESP_BROWNOUT_DET_LVL=6
  CONFIG_ESP_PHY_MAX_WIFI_TX_POWER=8
  CONFIG_ESP_PHY_MAX_TX_POWER=8
  CONFIG_ESP_PHY_REDUCE_TX_POWER=y
  CONFIG_ESP_PHY_RF_CAL_PARTIAL=y
  CONFIG_BT_ENABLED=y
  CONFIG_BT_BLE_ENABLED=y
  CONFIG_BT_CLASSIC_ENABLED=n
  CONFIG_BT_BLE_42_FEATURES_SUPPORTED=y
  CONFIG_BT_NIMBLE_ENABLED=y
  CONFIG_BT_NIMBLE_MAX_CONNECTIONS=3
  CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_INTERNAL=y
  CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_EFF=0
  CONFIG_ESP_TASK_WDT_TIMEOUT_S=10
  CONFIG_ESP_WIFI_ENABLED=y
  CONFIG_ESP_WIFI_SOFTAP_SUPPORT=y
  CONFIG_ESP_WIFI_STATION_ENABLED=y
  CONFIG_ESP_COEX_ENABLED=y
  CONFIG_ESP_WIFI_COEXIST_ENABLE=y
  CONFIG_ESP_COEX_SW_COEXIST_ENABLE=y
  CONFIG_ESP_WIFI_STA_DISCONNECTED_PM_ENABLE=y
  CONFIG_ESP_WIFI_SCAN_CACHE_SIZE=6
  CONFIG_ESP_INSIGHTS_ENABLED=n
  CONFIG_ESP_DIAGNOSTICS_ENABLED=n

[sdkcfg_wifi_on_nocal]
custom_sdkconfig =
  CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_80=y
  CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ=80
  CONFIG_PM_ENABLE=y
  CONFIG_ESP_BROWNOUT_DET=y
  CONFIG_ESP_BROWNOUT_DET_LVL=6
  CONFIG_ESP_PHY_MAX_WIFI_TX_POWER=8
  CONFIG_ESP_PHY_MAX_TX_POWER=8
  CONFIG_ESP_PHY_REDUCE_TX_POWER=y
  CONFIG_BT_ENABLED=y
  CONFIG_BT_BLE_ENABLED=y
  CONFIG_BT_CLASSIC_ENABLED=n
  CONFIG_BT_BLE_42_FEATURES_SUPPORTED=y
  CONFIG_BT_NIMBLE_ENABLED=y
  CONFIG_BT_NIMBLE_MAX_CONNECTIONS=3
  CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_INTERNAL=y
  CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_EFF=0
  CONFIG_ESP_TASK_WDT_TIMEOUT_S=10
  CONFIG_ESP_WIFI_ENABLED=y
  CONFIG_ESP_WIFI_SOFTAP_SUPPORT=y
  CONFIG_ESP_WIFI_STATION_ENABLED=y
  CONFIG_ESP_PHY_RF_CAL_PARTIAL=y
  CONFIG_ESP_PHY_RF_CAL_FULL=n
  CONFIG_ESP_PHY_RF_CAL_NONE=n
  CONFIG_ESP_PHY_CALIBRATION_AND_DATA_STORAGE=y
  CONFIG_ESP_INSIGHTS_ENABLED=n
  CONFIG_ESP_DIAGNOSTICS_ENABLED=n